### ISSUE TITLE
403 permission error even when logged in

### ISSUE THREAD

**Issue by vnl** [shahednasser/mongodb-realm-tutorial#1]
Following your instructions on user roles within Realm, I am facing the 403 permission error even when logged in. 
![image](https://user-images.githubusercontent.com/1355466/126335174-1b2c0987-863c-4afa-aeb3-02d6eeffd51c.png)

Just to be sure, I created 2 roles: User and user
![image](https://user-images.githubusercontent.com/1355466/126335554-fa660765-2736-4bdb-95b5-367341984acc.png)

User activity shows the following error:
![image](https://user-images.githubusercontent.com/1355466/126335772-f1c87cbe-61da-4755-a8da-50399b99ea22.png)

Any suggestions for this?

**Comment by shahednasser** [comment]
Hi @vnl sorry for the late reply. You need to make sure that the user that has write permissions has a higher priority that the user that has read permissions. This is because if the user with only read permissions has a higher priority, the user logging in will be considered that user and they will not have write permissions.

To change priorities, click on the arrow below the user role name to change the priority.
